### ISSUE TITLE
Test web interface

### ISSUE THREAD

**Issue by HermanFedaia** [robertrongen/smartys#51]

**Comment by HermanFedaia** [comment]
Algemene beeld: 

Findings:
1. Vaststelling Transport tokens onduidelijk (MUST HAVE).
Ik constateer:
- Voor km: 100 + 2 per km.
- Voor aantal dozen: 1 (vast aantal).
Dit kost al veel tijd om het uit te leggen en gaat onnodige vragen opleveren van de deelnemers. Het moet simpeler. Mijn voorstel:
- Per km: 2.
- Per doos: 5.
Dat is ondubbelzinnig, is makkelijk uit te leggen en snapt iedereen.

2. De kleur van het veld 'Maximaal gemeten temperatuur' verandert niet altijd correct als er een nieuwe waarde wordt ingevoerd (MUST HAVE)
Testsituatie:
Lage max temp: 10
Hoge max temp: 20

Invoer Max gemeten temp: 10
Kleur: groen
Resultaat: ok

Invoer Max gemeten temp: 15
Kleur: oranje
Resultaat: ok

Invoer Max gemeten temp: 21
Kleur: rood
Resultaat: ok

Invoer Max gemeten temp: 15
Kleur: oranje
Resultaat: ok

Invoer Max gemeten temp: 10
Kleur: groen
Resultaat: ok

Invoer Max gemeten temp: 9
Kleur: rood
Resultaat: NOT OK !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoer Max gemeten temp: 16
Kleur: oranje
Resultaat: ok

Invoer Max gemeten temp: 7
Kleur: rood
Resultaat: NOT OK !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

3. Toon het aantal tokens per km op het scherm (COULD HAVE).

4. RESET werkt niet of werking is niet duidelijk (SHOULD HAVE).
Er verandert niks op het scherm als ik op RESET druk.

**Comment by robertrongen** [comment]
1. en 3. Token waardes aangepast en worden nu ook getoond
2. was en bug en is opgelost
4. Reset knop was een dummy en is weggehaald. Reset kan al eenvoudig door het scherm te verversen
